name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: install code
        run: npm install
      - name: Checkout code
        run: make lint