name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: install code
        run: make install
      - name: publish code
        run: make publish
      - name: Checkout code
        run: make lint